### ISSUE TITLE
Check out

### ISSUE THREAD

**Issue by BernieHuang2008** [BernieHuang2008/scratch2py#1]
Check if it's acceptable and give some suggestions.
一个模板可以让我们更好地编写compiler，所以最好早点确定下来。我的意见都写在注释里了，你如果有什么建议就直接改模板，或者微信告诉我。（现在是电脑课，我只能上github）
ref to: https://github.com/BernieHuang2008/scratch2py/commit/90ac36d16083c315990151d752a97777e588c011

@cxzlw 

-- hg

**Comment by cxzlw** [comment]
我有个小小的看法，因为我们的库不是专供sc转的代码调的
所以为了更接近python库的使用方式，onGF只写一个，但是里面的代码call剩下的onGF_1, onGF_2
