### ISSUE TITLE
请出个教程，thanks

### ISSUE THREAD

**Issue by fzlzjerry** [BernieHuang2008/scratch2py#5]
这这这完全不到怎么下手，摆了

**Comment by BernieHuang2008** [comment]
1. 把`.sb3`的后缀名改为`.zip`，并解压
2. 从压缩包里找到`projects.json`，放到[sc3py/compiler/source/](https://github.com/BernieHuang2008/sc3py/tree/main/sc3py/compiler/source)文件夹下
3. 直接运行[sc3py/compiler/compiler.py](https://github.com/BernieHuang2008/sc3py/blob/main/sc3py/compiler/compiler.py)
4. 查看结果：打开[sc3py/compiler/result/main.py](https://github.com/BernieHuang2008/sc3py/blob/main/sc3py/compiler/result/main.py)文件，查看编译后的代码。该文件夹中的scgame是为了保证不出红线（syntax error）而写的临时库，一点用都没有，`main.py`是目前的唯一成果。

**Comment by fzlzjerry** [comment]
我有个问题，就是现在的这个项目缺少了什么东西，就是我和老王可以帮到你什么

From: Jinyuan Huang ***@***.***>
Date: Monday, July 1, 2024 at 8:25 PM
To: BernieHuang2008/sc3py ***@***.***>
Cc: Morax ***@***.***>, Author ***@***.***>
Subject: Re: [BernieHuang2008/sc3py] 请出个教程，thanks (Issue #5)

  1.  把.sb3的后缀名改为.zip，并解压
  2.  从压缩包里找到projects.json，放到sc3py/compiler/source/<https://github.com/BernieHuang2008/sc3py/tree/main/sc3py/compiler/source>文件夹下
  3.  直接运行sc3py/compiler/compiler.py<https://github.com/BernieHuang2008/sc3py/blob/main/sc3py/compiler/compiler.py>
  4.  查看结果：打开sc3py/compiler/result/main.py<https://github.com/BernieHuang2008/sc3py/blob/main/sc3py/compiler/result/main.py>文件，查看编译后的代码。该文件夹中的scgame是为了保证不出红线（syntax error）而写的临时库，一点用都没有，main.py是目前的唯一成果。
